functions:
  torch:
    attention:
      - softmax
    ffn:
      - silu
      - gelu
      - fast_gelu
  vlp:
    attention:
      - softmax
    ffn:
      - silu
      - gelu
      - fast_gelu
  pwl:
    attention:
      - softmax
    ffn:
      - silu
      - gelu
      - fast_gelu
  pwl_mobilenet:
    ffn:
      - silu
  taylor:
    attention:
      - softmax
params:
  vlp:
    attention:
      exp_dim: [8, 9, 10, 11, 12]
      max_exp: [-4, -3, -2, -1, 0, 1, 2, 3, 4]
      min_exp: [-4]
      window_size: [256]
      lut_build: ['max']
    ffn:
      exp_dim: [8, 9, 10, 11, 12]
      max_pos_exp: [-4, -3, -2, -1, 0, 1, 2, 3, 4]
      max_neg_exp: [-4, -3, -2, -1, 0, 1, 2, 3, 4]
      window_size: [256]
  pwl:
    attention:
      segments: [8, 10, 12, 14, 16, 18, 20, 22]
      segment_0: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26]
    ffn:
      segments: [8, 10, 12, 14, 16, 18, 20, 22]
      segment_0: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26]
  taylor:
    attention:
      degree_center: [-8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, ]
      degrees: [3, 4, 5, 6, 7, 8, 9, 10]
