nlp:
  datasets:
    c4:
      dataset: allenai/c4
      config: en
      split: validation
  models:
    - meta-llama/Llama-2-7b-hf
    # - meta-llama/Llama-2-13b-hf
    # - meta-llama/Llama-2-70b-hf
    - meta-llama/Llama-3.1-8B
    # - meta-llama/Llama-3.1-70B
    # - meta-llama/Llama-3.1-405B
audio:
  datasets:
    librispeech:
      dataset: openslr/librispeech_asr
      split: test.clean
  models:
    # - openai/whisper-tiny
    # - openai/whisper-small
    - openai/whisper-base
    # - openai/whisper-medium
    # - openai/whisper-large
vision_1:
  datasets:
    imagenet-1k:
      dataset: imagenet-1k
      split: validation
  models:
    - microsoft/swinv2-tiny-patch4-window8-256
    # - microsoft/swinv2-small-patch4-window8-256
    # - microsoft/swinv2-base-patch4-window8-256
# vision_2:
#   datasets:
#     imagenet-22k:
#       dataset: timm/imagenet-22k-wds
#       split: validation
#   models:
#     - microsoft/swinv2-large-patch4-window12-192-22k
video:
  datasets:
    kinetics:
      dataset: nateraw/kinetics
      split: validation
  models:
    - google/vivit-b-16x2
    # - google/vivit-b-16x2-kinetics400