torch:
  attention:
    path: 'torch/softmax/'
  ffn:
    path: 'torch/silu/'
vlp:
  attention:
    exp_dim: [8, 12]
    max_exp: [-4, 4]
    min_exp: [-7, 1]
    window_size: 8
    lut_build: ['max', 'min']
    path: 'vlp/softmax/'
  ffn:
    exp_dim: [8, 12]
    max_exp: [-4, 4]
    min_exp: [-7, 1]
    window_size: 8
    lut_build: ['max', 'min']
    path: 'vlp/softmax/'
pwl:
  attention:
    segments: [6, 26]
    segment_0: [2, 26]
    path: 'pwl/softmax/'
  ffn:
    segments: [6, 26]
    segment_0: [2, 26]
pwl_mobilenet:
  ffn:
    path: 'pwl_mobilenet/silu/'
taylor:
  attention:
    degree_center: [-10, 10]
    degrees: [2, 26]
    path: 'taylor/softmax/'
