dataset:
  name: c4
  hf_path: allenai/c4
  config: en
  split: validation
model: 
  name: meta-llama/Llama-3.1-8B
  modality: nlp
nonlinear:
  attention: softmax
  ffn: silu
parameters:
  batch_size: 1