functions:
  vlp:
    ffn: [silu, gelu, fast_gelu]
params:
  vlp:
    ffn:
      exp_dim: [8, 9]
      max_pos_exp: [4]
      min_pos_exp: [-8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2]
      window_size: [256]
      lut_build: [min]
