dataset:
  name: librispeech
  hf_path: openslr/librispeech_asr
  split: test.clean
model: 
  name: openai/whisper-tiny
  modality: audio
nonlinear:
  attention: softmax
  ffn: gelu
parameters:
  batch_size: 125